### ISSUE TITLE
How to config permission

### ISSUE THREAD

**Issue by ShoShi23** [KarlOfDuty/CustomLoadouts#5]
I have 100% chance for coin and i don't get it...

My config:
```yaml
# Prints a confirmation whenever a player is given a loadout
verbose: true
# Prints debug messages
debug: false
# Adds a ms delay if needed for plugin compatibility
delay: 0

# This sets up the loadouts and the permission nodes required to get them
# For instance "customloadouts.donatorloadouts" gives all loadouts under the donatorloadouts node below, as long as the class and chance checks are successful.
customloadouts:
    sponsorloadouts:
        CLASSD:
            - 100:
                - COIN 
            - 10:
                - MEDKIT
                - FLASHLIGHT
                - RADIO
                - ZONE_MANAGER_KEYCARD
            - 5:
                - COM15_PISTOL
        SCIENTIST:
            - 100:
                - COIN 
            - 10:
                - REMOVEITEMS
                - REMOVEAMMO
                - MEDKIT
                - FLASHLIGHT
                - RADIO
                - ZONE_MANAGER_KEYCARD
            - 5:
                - REMOVEITEMS
                - REMOVEAMMO
                - COM15_PISTOL
                - DROPPED_9
                - DROPPED_9
```
